// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-auxiliary-line-snap/index.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-auxiliary-line-snap/index.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-scale-customization/index.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-scale-customization/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-action-config/index.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-action-config/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-custom-style/index.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-custom-style/index.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-auto-scroll/index.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-auto-scroll/index.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-basic-event/index.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-basic-event/index.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-scroll-sync/index.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-scroll-sync/index.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-grid-snap/index.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-grid-snap/index.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-callback/index.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-callback/index.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-basic/index.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-basic/index.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/engine/index.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/engine/index.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/engine/api.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/engine/api.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/index.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/index.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/data.md?type=frontmatter';
import { demoIndex as dmi13 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/data.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/todo.md?type=frontmatter';
import { demoIndex as dmi14 } from '/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/todo.md?type=demo-index';

export const filesMeta = {
  'docs/editor-demo/editor-auxiliary-line-snap/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-auxiliary-line-snap/index.md?type=text'),
  },
  'docs/editor-demo/editor-scale-customization/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-scale-customization/index.md?type=text'),
  },
  'docs/editor-demo/editor-action-config/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-action-config/index.md?type=text'),
  },
  'docs/editor-demo/editor-custom-style/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-custom-style/index.md?type=text'),
  },
  'docs/editor-demo/editor-auto-scroll/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-auto-scroll/index.md?type=text'),
  },
  'docs/editor-demo/editor-basic-event/index': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-basic-event/index.md?type=text'),
  },
  'docs/editor-demo/editor-scroll-sync/index': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-scroll-sync/index.md?type=text'),
  },
  'docs/editor-demo/editor-grid-snap/index': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-grid-snap/index.md?type=text'),
  },
  'docs/editor-demo/editor-callback/index': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-callback/index.md?type=text'),
  },
  'docs/editor-demo/editor-basic/index': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/editor-demo/editor-basic/index.md?type=text'),
  },
  'docs/engine/index': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/engine/index.md?type=text'),
  },
  'docs/engine/api': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/engine/api.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/index.md?type=text'),
  },
  'docs/data': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/data.md?type=text'),
  },
  'docs/todo': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/mrlgm/Project/react-timeline-editor/packages/document/docs/todo.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
