# afterInstall: yarn husky && yarn workspaces foreach --all run prepare

compressionLevel: mixed

enableColors: true

enableGlobalCache: false

conditions:
    USE_SRC:
        default: false

nodeLinker: node-modules

checksumBehavior: update

npmPublishRegistry: 'https://registry.npmmirror.com/'

npmRegistryServer: 'https://registry.npmmirror.com/'

plugins:
  - checksum: 40e072a2f71bd4638ee0f69f2d974477732f5e1c64b786b8f09b296d39cda7cbf503f355c6843e11f95480ae926009b0f6aa46b5a43821c3e005c9ef81c4ad57
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js'
  - path: .yarn/plugins/@yarnpkg/plugin-conditions.cjs
    spec: 'https://raw.githubusercontent.com/nicolo-ribaudo/yarn-plugin-conditions/main/bundles/%40yarnpkg/plugin-conditions.js'

# yarnPath: .yarn/releases/yarn-4.9.2.cjs

# changesetBaseRefs:
#   - master
#   - origin/master
#   - develop
#   - origin/develop

# changesetIgnorePatterns:
#   - '**/*.test.{js,ts}'
#   - '!packages/**/*'
